spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
            - GET
            - POST
            - PATCH
            - DELETE
            - OPTIONS
            - PUT
        add-to-simple-url-handler-mapping: true
