spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/api/authenticate]':
            allowedOrigins: http://localhost:3000
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
