spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
