spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - PATCH
            - DELETE
            - OPTIONS
            - PUT
        add-to-simple-url-handler-mapping: true
